---
title: "Examples"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
---

This section shows how to use the exaples available in the [github.com/d3/d3/wiki/Gallery](https://github.com/d3/d3/wiki/Gallery) gallery.

## Bubbles

[bl.ocks.org/mbostock/4063269](https://bl.ocks.org/mbostock/4063269)

```{r}
flares <- read.csv(system.file("samples/bubbles/flare.csv", package = "r2d3"))
r2d3::r2d3(
  flares[!is.na(flares$value), ],
  system.file("samples/bubbles/bubbles.js", package = "r2d3"),
  version = 4
)
```

## Morley

[bl.ocks.org/mbostock/4061502](https://bl.ocks.org/mbostock/4061502)

```{r}
r2d3::r2d3(
  read.csv(system.file("samples/morley/morley.csv", package = "r2d3")),
  system.file("samples/morley/morley.js", package = "r2d3"),
  version = 3,
  tag = "div",
  dependencies = c(
    system.file("samples/morley/morley.css", package = "r2d3"),
    system.file("samples/morley/box.js", package = "r2d3")
  )
)
```


## Bullets

[bl.ocks.org/mbostock/4061961](https://bl.ocks.org/mbostock/4061961)

```{r}
r2d3::r2d3(
  jsonlite::read_json(system.file("samples/bullets/bullets.json", package = "r2d3")),
  system.file("samples/bullets/bullets.js", package = "r2d3"),
  version = 3,
  tag = "div",
  dependencies = c(
    system.file("samples/bullets/bullets.css", package = "r2d3"),
    system.file("samples/bullets/helper.js", package = "r2d3")
  ),
  height = 300
)
```

## Calendar

[bl.ocks.org/mbostock/4063318](https://bl.ocks.org/mbostock/4063318)

```{r}
r2d3::r2d3(
  read.csv(system.file("samples/calendar/dji.csv", package = "r2d3")),
  system.file("samples/calendar/calendar.js", package = "r2d3"),
  version = 4,
  tag = "div",
  height = 1950
)
```