---
title: "Gallery: Map-with-Latitude-Longitude"
---

```{r setup, include=FALSE}
library(r2d3)
knitr::opts_chunk$set(echo=FALSE, comment=NA)
```

<div id="source-link">
<https://github.com/rstudio/r2d3/tree/master/vignettes/gallery/Map-with-Latitude-Longitude>
</div>

<div class="row">

<div class="col-sm-3">
<div class="list-group">
  <a href="../bubbles/" class="list-group-item">bubbles</a>
  <a href="../bullets/" class="list-group-item">bullets</a>
  <a href="../calendar/" class="list-group-item">calendar</a>
  <a href="../cartogram/" class="list-group-item">cartogram</a>
  <a href="../chord/" class="list-group-item">chord</a>
  <a href="../circlepacking/" class="list-group-item">circlepacking</a>
  <a href="../dendogram/" class="list-group-item">dendogram</a>
  <a href="../forcegraph/" class="list-group-item">forcegraph</a>
  <a href="../morley/" class="list-group-item">morley</a>
  <a href="../population/" class="list-group-item">population</a>
  <a href="../radialtree/" class="list-group-item">radialtree</a>
  <a href="../stackedbars/" class="list-group-item">stackedbars</a>
  <a href="../streamgraph/" class="list-group-item">streamgraph</a>
  <a href="../sunburst/" class="list-group-item">sunburst</a>
  <a href="../treemap/" class="list-group-item">treemap</a>
  <a href="../voronoi/" class="list-group-item">voronoi</a>
  <a href="../Map-with-Latitude-Longitude/" class="list-group-item">Map-with-Latitude-Longitude</a>
  
</div>
</div>

<div class="col-sm-9">

```{r, echo=TRUE, eval=FALSE}
r2d3(data = jsonlite::read_json("test.json"),css = "map.css", d3_version = 3, dependencies = c("topojson.min.js", "http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js"), script = "map.js")
```

```{r, echo=FALSE}
r2d3(data = jsonlite::read_json("test.json"),css = "map.css", d3_version = 3, dependencies = c("topojson.min.js", "http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js"), script = "map.js")
```


####  Map.js

```{r, results='asis'}
cat("```js\n")
writeLines(readLines("map.js", warn = FALSE))
cat("```\n")
```

#### Map.css

```{r, results='asis'}
cat("```css\n")
writeLines(readLines("map.css", warn = FALSE))
cat("```\n")
```


</div>

</div>


```{js}
$('#source-link').appendTo($('.page-header')).css('display', 'block');
$('.template-vignette>.row>.col-md-9').attr('class', 'col-md-12');
$('a.list-group-item[href="../Map-with-Latitude-Longitude/"]').addClass('active');
$('a[href="../../../articles/gallery.html"]').parent().addClass('active');
```


